#348391 Отметка "Утверждено" для договора
DirectumCompany/rx-examples pull request #20
Opened 2024-08-08 13:09 UTC by Kovalev-MK

Пример перекрытия в поротом штампа

2024-08-08 13:25 UTC, VieroDePopoda commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    private static string GeApprovedMarkAsHtml(IOfficialDocument document, long versionId)
Опечатка

2024-08-09 08:17 UTC, diamtr requested changes

2024-08-09 08:17 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    public virtual void GetMarkForIncomingInvoiceDocument()
Почему метод GetSome это void?

2024-08-09 08:17 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    public virtual void CreateAndSaveMark(string markKindSid, double xIndent, double yIndent, int rotation, int page)
Для чего выделять этот отдельный метод, а не делать создание по месту?

2024-08-09 08:17 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +        html = html.Replace("{approvedBy}", employee.Department.BusinessUnit.Name);
Возможно это действительно так надо, но approvedBy это ФИО человека, а передается туда наименование НОР.
Выглядит максимально странно

2024-08-09 08:17 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +      string html;
var html = string.Empty, порфавор

2024-08-09 08:17 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/OfficialDocument/OfficialDocumentServerFunctions.cs
> +      if (Contracts.Is(_obj))
Почему здесь, а не в договорах перекрыто?

2024-08-09 08:17 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Sungero.Docflow/ModuleInitializer.cs
> +      CreateMarkKind(Sungero.Examples.Contracts.Resources.ApprovedMarkName, Sungero.Examples.Constants.Contracts.Contract.ApprovedMarkKindSid,
Approved - не дает мне понять, что это именно "постраничное парафирование". Эти самые отметки об Approved бывают разные.
Если согласовали так, то ок. Но если еще нет - предлагаю подумать над неймингом.

2024-08-11 17:52 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    private static string GeApprovedMarkAsHtml(IOfficialDocument document, long versionId)
Исправил, перенес перекрытие в договоры

2024-08-11 17:52 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Shared/Contract/ContractConstants.cs
> +    public const string ApprovedMarkKindMethod = "GeApprovedMarkAsHtml";
Исправил, перенес перекрытие в договоры

2024-08-11 17:53 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    public virtual void CreateAndSaveMark(string markKindSid, double xIndent, double yIndent, int rotation, int page)
Исправил, перенес перекрытие в договоры

2024-08-11 17:53 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +      string html;
Исправил, перенес перекрытие в договоры

2024-08-12 12:11 UTC, diamtr requested changes
Дополнительно:
перенацель ПР на 4.11, плиз

2024-08-12 12:11 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +      if (_obj.LastVersionApproved ?? false)
Иначе ее нужно удалить

2024-08-12 12:11 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +        mark.Page = 0;
Должно падать на текущем мастере.
Как реализуется поворот - понимаю с учетом ПРа в прикладную. Постраничность не понимаю пока что.

2024-08-13 04:56 UTC, VieroDePopoda commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +      if (_obj.LastVersionApproved ?? false)
Можно еще написать вот так _obj.LastVersionApproved == true
Результат тот же, но стало немного читабельнее

2024-08-15 11:06 UTC, VieroDePopoda commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    private static string GetApprovedMarkAsHtml(Sungero.Docflow.IOfficialDocument document, long versionId)
Попробуй переделать в public virtual

2024-08-15 11:06 UTC, VieroDePopoda commented on src/Packages/Sungero.Examples/Sungero.Examples.Shared/Contract/ContractConstants.cs
> +    public const string PaginalApproveMarkKindClass = "Sungero.Examples.Server.ContractFunctions";
Sungero.Examples.Functions.Contract

2024-08-18 21:25 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Contract/ContractServerFunctions.cs
> +    private static string GetApprovedMarkAsHtml(Sungero.Docflow.IOfficialDocument document, long versionId)
Отметка скипалась из-за пустого контента. Не находит функцию

2024-08-18 21:25 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Shared/Contract/ContractConstants.cs
> +    public const string PaginalApproveMarkKindClass = "Sungero.Examples.Server.ContractFunctions";
Не находит функцию

2024-08-19 08:27 UTC, diamtr approved these changes

2024-08-19 10:13 UTC, merged