User Story 348175: PDF. Examples. Простановка отметок об ЭП на служебной записке
DirectumCompany/rx-examples pull request #23
Opened 2024-08-18 21:33 UTC by Kovalev-MK

[User Story 348175](https://rxtfs.directum.ru/is-builder8/Directum%20RX/_workitems/edit/348175): PDF. Examples. Простановка отметок об ЭП на служебной записке

2024-08-22 08:00 UTC, diamtr requested changes

2024-08-22 08:00 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +    public override Sungero.Docflow.Structures.OfficialDocument.IConversionToPdfResult ConvertToPdfWithMarks(long versionId)
Кажется, что не будет работать с коробочной отметкой об ЭП.
То есть будет микс из коробочной ЭП и всех подписей по служебке.
Подумай как обойти этот момент.
Если на служебке только одна подпись, то она должна все равно ставится как на картинке. Всё то же самое, если подписей несколько. Кажется, что тут можно попробовать перекрыть создание/удаление стандартной отметки об ЭП, чтобы получить остальные доп подписи тут надо как-то исключать уже проставленную и подумать про удаление этих дополнительных.

2024-08-22 08:00 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Shared/Mark/Mark.mtd
> +      "Name": "SignatureIdSungero",
Кажется, что не нужно спецсвойства, характерные для какого-то конкретного вида отметок вводить. Лучше пользоваться AdditionalParams.

2024-08-23 08:30 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +    public override Sungero.Docflow.Structures.OfficialDocument.IConversionToPdfResult ConvertToPdfWithMarks(long versionId)
Перекрыл метод получения или создания отметок об ЭП для служебных

2024-08-23 11:06 UTC, diamtr requested changes

2024-08-23 11:06 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +      var signatures = this.GetDocumentSignatures(versionId);
А как отбирается, что надо создавать такие отметки для всех подписей кроме первой, которая зайдет по отметке об ЭП?

2024-08-25 21:02 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +        var additionalParam = mark.AdditionalParams.AddNew();
Поправил

2024-08-25 21:03 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +      var signatures = this.GetDocumentSignatures(versionId);
По id подписи в доп параметрах. Перекрыл базовое создание отметки об ЭП для служебок стр. 77 GetOrCreateSignatureMark

2024-08-25 21:03 UTC, Kovalev-MK commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Mark/MarkServerFunctions.cs
> +    public static IMark GetOrCreateMark(Sungero.Docflow.IOfficialDocument document, string markKindSid, Sungero.Domain.Shared.ISignature signature)
Поправил

2024-08-27 09:25 UTC, diamtr requested changes

2024-08-27 09:25 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +                              m.AdditionalParams.Any(a => a.Name == PublicConstants.Docflow.Memo.MarkSignatureIdKey && a.Value == signature.Id.ToString())).FirstOrDefault();
Лучше отдельно это вычислять. Были проблемы с трансляцией методов в гибер

2024-08-27 09:25 UTC, diamtr commented on src/Packages/Sungero.Examples/Sungero.Examples.Server/Memo/MemoServerFunctions.cs
> +      return mark;
Перед тем как вернуть еще наверное надо ИД подписи в AdditionalParams засунуть

2024-08-28 08:39 UTC, diamtr approved these changes

2024-08-28 09:03 UTC, merged